added inspection list screen. resolves #113
Nesteo/Nesteo-App pull request #115
Opened 2019-10-26 17:06 UTC by SimonSchwierzeck

2019-10-26 17:37 UTC, SimonOyen commented
PR blocked until #86 is closed.

2019-10-26 17:44 UTC, SimonOyen requested changes
Please look into the problem with files in the docs/ directory and implement the InspectionByNestingBoxId functionality.

2019-10-26 17:44 UTC, SimonOyen commented on lib/blocs/inspectiondata_bloc/inspectiondata_bloc.dart
> +      yield InspectionReadyState();
Has to be changed to InspectionPreviewByNestingBoxId when #86 is resolved

2019-10-27 12:52 UTC, SimonSchwierzeck commented
Please dont break other peoples repositorys.

2019-10-28 12:58 UTC, SimonOyen approved these changes
:medal_sports:

2019-10-28 13:00 UTC, merged